// <auto-generated />
namespace RemoteWork.Access.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class uniqueadded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(uniqueadded));
        
        string IMigrationMetadata.Id
        {
            get { return "201602110537092_unique-added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
